config/routes.rb
Rails.application.routes.draw do

  root 'welcome#about'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks", passwords: 'users/passwords' }
  resources :chatrooms, param: :slug
  resources :messages
  resources :pictures
  resources :memes
  resources :votes
  resources :chatroom_players
  get ':slug/waiting', to: "chatrooms#waiting"
  get ':slug/meme', to: "chatrooms#meme"
  get ':slug/vote', to: "chatrooms#vote"
  get ':slug/winner', to: "chatrooms#winner"
  get ':slug', to: 'chatrooms#show'
  post ':slug/addarnold', to: 'chatroom_players#addarnold'
  post ':slug/removearnold', to: 'chatroom_players#removearnold'
  post 'chatrooms/join', to: 'chatrooms#join'

  
  mount ActionCable.server => '/cable'

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :message_writers,
    through: :messages,
    source: :chatroom_players,
    class_name: "ChatroomPlayer"
  # Chatroom has many ChatroomPictures, Pictures through ChatroomPictures
  has_many :chatroom_pictures, dependent: :destroy
  has_many :pictures, through: :chatroom_pictures

  has_many :chatroom_players, dependent: :destroy
  has_many :players,
    through: :chatroom_players,
    source: :user,
    class_name: "User"

  before_validation :slugify, :sanitize
  validates :slug, presence: true, uniqueness: true, case_sensitive: false

  def to_param
    self.slug
  end

  def slugify
    rando = (0...5).map { (65 + rand(26)).chr }.join
    self.slug = rando
  end

  def sanitize
    if self.topic.length > 1
      self.private = false
    else
      self.private = true
    end
    self.topic = self.topic.strip.downcase.gsub(" ", "-")
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def join
    if Chatroom.find_by(slug: params[:slug].upcase)
      @chatroom = Chatroom.find_by(slug: params[:slug].upcase)
      redirect_to "/#{@chatroom.slug}"
      return
    else
      respond_to do |format|
        flash[:notice] = {error: ["That game does not exist. Please try again."]}
        format.html { redirect_to :back}
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save!
      offset = rand(Picture.count)
      rando_picrissian = Picture.offset(offset).first
      @chatroom_picture = ChatroomPicture.new(chatroom: @chatroom, picture: rando_picrissian)
      if @chatroom_picture.save!
        respond_to do |format|
          format.html { redirect_to "/#{@chatroom.slug}" }
          format.js { redirect_to "/#{@chatroom.slug}" }
        end
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["A game with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def waiting

    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
    # Register Player To Game
    @current_player = ChatroomPlayer.where(user_id: current_user.id, chatroom_id: @chatroom.id)
    if @current_player.length > 0
      @chatroom_player = @current_player[0]
    else
      @chatroom_player = ChatroomPlayer.new
      @chatroom_player.user_id = current_user.id
      @chatroom_player.chatroom_id = @chatroom.id
      @chatroom_player.playername = current_user.username
      @chatroom_player.status = "new"
      if @chatroom.players.length == 0
        @chatroom_player.creator = true
      end
      if @chatroom_player.save!
      # Establish Readiness In Case Of New Player
      @players = ChatroomPlayer.where(chatroom_id: @chatroom.id)
      @ready_players = ChatroomPlayer.where(chatroom_id: @chatroom.id, status: "ready")
      # Shout it from the rooftops
        flash[:notice] = "Successfully joined game"
        ActionCable.server.broadcast "chatrooms_#{@chatroom.slug}",
          username: current_user.username,
          status: @chatroom_player.status
      return
      end
    end
    # Establish Readiness In Case Of Existing Player
    @players = ChatroomPlayer.where(chatroom_id: @chatroom.id)
    @ready_players = ChatroomPlayer.where(chatroom_id: @chatroom.id, status: "ready")
    # New Picture If This Is Not A New Game
    if @chatroom_player.creator == true && ChatroomPicture.where(chatroom: @chatroom, winner: true).length == ChatroomPicture.where(chatroom: @chatroom).length
      offset = rand(Picture.count)
      rando_picrissian = Picture.offset(offset).first
      @new_chatroom_picture = ChatroomPicture.new(chatroom: @chatroom, picture: rando_picrissian)
      @new_chatroom_picture.save!
    end
    # Arnold
    if @chatroom_player.creator == true
      @arnolds = []
      @arnold = ChatroomPlayer.where(playername: "Arnold", chatroom: @chatroom).first
      @schwarzenegger = ChatroomPlayer.where(playername: "Schwarzenegger", chatroom: @chatroom).first
      if @arnold
        @arnolds << @arnold
      end
      if @schwarzenegger
        @arnolds << @schwarzenegger
      end
    end
  end

  def winner


    @chatroom = Chatroom.find_by(slug: params[:slug])
    @current_player = ChatroomPlayer.where(user_id: current_user.id, chatroom_id: @chatroom.id)
    @chatroom_player = @current_player[0]
    @chatroom_player.status = "unready"
    @chatroom_player.save!

    @chatroom_picture = ChatroomPicture.where(chatroom: @chatroom).last
    @memes = @chatroom_picture.memes

    meme_array = []
    @memes.each do |meme|
      if meme_array.length == 0
        meme_array << meme
      else
        if meme.votes.count > meme_array[0].votes.count
          meme_array.pop
          meme_array << meme
        end
      end
    end

    @winner = meme_array[0]
    if @chatroom_player.creator == true && @chatroom_picture.winner != true
      @winner.winner = true
      @winner.save!
      @chatroom_picture.winner = true
      @chatroom_picture.save!
    end

  end

  def meme
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @current_player = ChatroomPlayer.where(user_id: current_user.id, chatroom_id: @chatroom.id)
    @chatroom_player = @current_player[0]
    @meme = Meme.new
    @message = Message.new
    @chatroom_picture = ChatroomPicture.where(chatroom: @chatroom).last
    if Meme.where(chatroom_player_id: @chatroom_player.id, chatroom_picture_id: @chatroom_picture.id).length < 1
       @chatroom_player_meme = "doesn't exist"
    end
    @ready_player_count = ChatroomPlayer.where(chatroom_id: @chatroom.id, status: "ready").length
    # Detect Arnold
    if @chatroom_player.creator == true
      @arnolds = []
      @arnold = ChatroomPlayer.where(playername: "Arnold", chatroom: @chatroom).first
      @schwarzenegger = ChatroomPlayer.where(playername: "Schwarzenegger", chatroom: @chatroom).first
      if @arnold
        @arnolds << @arnold
      end
      if @schwarzenegger
        @arnolds << @schwarzenegger
      end
      # Meme Arnold
      @arnolds.each do |arndawg|
        if Meme.where(chatroom_player_id: arndawg.id, chatroom_picture_id: @chatroom_picture.id).length < 1
          meme = Meme.new
          meme.caption = Arnold.quote
          meme.chatroom_player_id = arndawg.id
          meme.chatroom_picture_id = @chatroom_picture.id
          if meme.save!
            ActionCable.server.broadcast "memes_#{@chatroom.slug}",
              meme_status: "Meme"
          end
        end
      end
    end
    

  end

  def vote
    @vote = Vote.new
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @current_player = ChatroomPlayer.where(user_id: current_user.id, chatroom_id: @chatroom.id)
    @chatroom_player = @current_player[0]
    @message = Message.new
    @chatroom_picture = ChatroomPicture.where(chatroom: @chatroom).last
    @memes = @chatroom_picture.memes
    @own_meme = @chatroom_picture.memes.where(chatroom_player_id: @chatroom_player.id).last
    @memes = @memes - [@own_meme]

        # Detect Arnold
    if @chatroom_player.creator == true
      @arnolds = []
      @arnold = ChatroomPlayer.where(playername: "Arnold", chatroom: @chatroom).first
      @schwarzenegger = ChatroomPlayer.where(playername: "Schwarzenegger", chatroom: @chatroom).first
      if @arnold
        @arnolds << @arnold
      end
      if @schwarzenegger
        @arnolds << @schwarzenegger
      end
      # Meme Arnold
      if @arnolds.length > 0

        @arnolds.each do |arndawg|
          vote_count = 0
          @memes.each do |meme|
            if Vote.where(meme_id: meme.id, chatroom_player_id: arndawg.id).length > 0
              vote_count += 1
              puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" + vote_count + "PLAYERNAME:" + arndawg.playername + "$$$$$$$$$$$$$$" + "VOTING FOR:" + meme.caption
            end
          end
          if vote_count < 1
            vote = Vote.new
            vote.chatroom_player_id = arndawg.id
            eligible_votes = @chatroom_picture.memes.where.not(chatroom_player_id: arndawg.id)
            ev_rand = rand(eligible_votes.count)
            vote.meme_id = eligible_votes[ev_rand].id
            if vote.save!
              ActionCable.server.broadcast "memes_#{@chatroom.slug}",
                meme_status: "Vote"
            end
          end
        end

      end
    end
    @vote_count = 0
    @chatroom_picture.memes.each do |meme|
      @vote_count += meme.voters.length
    end
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug].upcase)
    if @chatroom.chatroom_pictures.length == 0 
      redirect_to "/#{@chatroom.slug}/waiting"
      return
    elsif @chatroom.pictures.length > 0
      if @chatroom.chatroom_pictures.last.memes.length > 2 && (@chatroom.chatroom_pictures.last.memes.length == @chatroom.chatroom_players.where(status: "ready").length)
        redirect_to "/#{@chatroom.slug}/vote"
        return
      elsif ((@chatroom.players.length > 2) && (@chatroom.chatroom_players.where(status: "ready").length == @chatroom.players.length))
        redirect_to "/#{@chatroom.slug}/meme"
        return
      end
        redirect_to "/#{@chatroom.slug}/waiting"
        return
    end
    @message = Message.new
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/views/chatrooms/_add_arnold.html.erb
<div class="chatrooms add-arnold-container">
    <%= form_tag("/#{chatroom.slug}/addarnold", remote: true, authenticity_token: true, method: "post", class: "form-horizontal") do %>
    <%= hidden_field_tag :arnoldcount, arnold_count %>
    <%= submit_tag("Add Arnold", class: "btn btn-primary", data: {send: "add-arnold"}) %>
    <% end %>
</div>

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_join.html.erb
<div class="chatrooms">
    <%= form_tag("/chatrooms/join", method: "post", class: "form-horizontal center col-xs-4 col-xs-offset-4") do %>
    <%= text_field_tag 'slug', nil, class: "form-control" %>
    <br><br>
    <%= submit_tag("Join Game", class: "btn btn-primary") %>
    <% end %>
</div>

app/views/chatrooms/_leave.html.erb
<%=form_for @chatroom_player, method: :delete, remote: true, authenticity_token: true do |f|%>
    <%= f.submit "Leave Game", class: "btn btn-danger", data: {send: "leave"} %>
    <%end%>

app/views/chatrooms/_ready.html.erb
<%=form_for @chatroom_player, remote: true, authenticity_token: true do |f|%>
  <%= f.hidden_field :username, value: current_user.username %>
  <%= f.hidden_field :status, value: "ready" %>
  <%= f.submit "Ready", class: "btn btn-primary", data: {send: "ready"} %>
<%end%>

app/views/chatrooms/_remove_arnold.html.erb
<div class="chatrooms remove-arnold-container">
    <%= form_tag("/#{chatroom.slug}/removearnold", remote: true, authenticity_token: true, method: "post", class: "form-horizontal") do %>
    <%= hidden_field_tag :arnoldcount, arnold_count %>
    <%= submit_tag("Remove Arnold", class: "btn btn-danger", data: {send: "remove-arnold"}) %>
    <% end %>
</div>

app/views/chatrooms/_unready.html.erb
<%=form_for @chatroom_player, remote: true, authenticity_token: true do |f|%>
  <%= f.hidden_field :username, value: current_user.username %>
  <%= f.hidden_field :status, value: "unready" %>
  <%= f.submit "Unready", class: "btn btn-danger", data: {send: "unready"} %>
<%end%>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/meme.html.erb
<div class="container">
  <div class="row col-xs-12 text-center">

    <h3>GAME CODE: <strong id="chatroom-slug"><%= @chatroom.slug %></strong></h3>
  </div>

    <p class="text-center">Memes to be submitted:</p>

  <div class="row text-center" id="memes-left-to-submit">
    <%= @ready_player_count - @chatroom_picture.memes.length %>
  </div>

  <div class="text-center">
    <%= image_tag @chatroom_picture.picture.url, height: "300" %>
        <h4>Meme This Photo</h4>
  </div>
  <br>
  <div class="text-center row col-xs-8 col-xs-offset-2">
    <div class="row">
      <% if @chatroom_player_meme %>
        <%= render partial: 'memes/meme_form' %>
      <% end %>
    </div>

  </div>



  <div class="row col-xs-8 col-xs-offset-2">
    <h1><%= @chatroom.topic %></h1>
    <div class="panel panel-default">
      <% if @chatroom.messages.any? %>
        <div class="panel-body" id="messages">
          <%= render @chatroom.messages %>
        </div>
      <%else%>
        <div class="panel-body hidden" id="messages">
        </div>
      <%end%>
    </div>
    <% if current_user %>
      <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom, chatroom_player: @chatroom_player}%>
    <% end %>
  </div>

</div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2 text-center">

  <h1 class="">Create a Game</h1>
    <div class="well">
<br><br>

      <div class="chatroom-form">
        <%= form_for @chatroom do |f| %>
          <div class="input-group">
            <span class="input-group-addon">topic:</span>
            <%= f.text_field :topic, class: "form-control"%>
          </div>
          <br>
          <%= f.submit "Create Game", class: "btn btn-primary", id: "create-game" %>
        <% end %>
      </div>
    </div>

</div>

app/views/chatrooms/show.html.erb
<div class="nav-offset container">
  <div class="row col-xs-12 text-center">
    <h1 id="chatroom-slug" value="<%= @chatroom.slug %>">GAME CODE: <%= @chatroom.slug %></h1>
  </div>
</div>
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render @chatroom.messages %>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>
  <% if current_user %>
    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
  <% end %>

</div>

app/views/chatrooms/vote.html.erb
<div class="row hidden" id="votes-left-to-submit">
  <%= @chatroom_picture.memes.length - @vote_count %>
</div>

<div class="row col-xs-12 text-center">
  <h3>GAME CODE: <strong id="chatroom-slug"><%= @chatroom.slug %></strong></h3>
</div>

<div class="text-center">
  <%= image_tag @chatroom_picture.picture.url, height: "300" %>
</div>


<div class="row col-xs-8 col-xs-offset-2 text-center" id="vote-for-captions">

    <% if @chatroom_player.votes.count < @chatroom.chatroom_pictures.count %>
  <h4>Vote For The Best Meme</h4>
  <div class="panel panel-default">

        <div class="panel-body" id="memes">
          <% @memes.shuffle.each do |meme| %> 
          <%= render partial: "memes/meme", locals: {meme: meme} %>
        <% end %>
        </div>

    <%else%>
      <div class="panel-body hidden" id="memes">
      </div>
    <%end%>
  </div>
</div>

<div class="row col-xs-8 col-xs-offset-2">
  <h1><%= @chatroom.topic %></h1>
  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render @chatroom.messages %>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>
  <% if current_user %>
    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom, chatroom_player: @chatroom_player}%>
  <% end %>
</div>

app/views/chatrooms/waiting.html.erb
<div class="row col-xs-12 text-center waiting-and-game-code-container">
  <h4>Waiting</h4>
  <h3>GAME CODE: <strong id="chatroom-slug"><%= @chatroom.slug %></strong></h3>
</div>

<div class='hidden' id='arnold-count'><%= @arnolds.length %></div>
<div class="row col-xs-8 col-xs-offset-2 ready-and-unready-column-container">
  <div class="panel panel-default col-xs-6">
  <h4>Players</h4>
  <div class="panel-body">
    <% if @players.any? %>
    <section class="" id="joined-players">
      <% @players.each do |player| %>
        <p id="player-<%= player.user.username %>"><%= render partial: 'players/show', locals: {player: player} %></p>
      <% end %>
    </section>
    </div>
  </div>
    <%else%>
        <div class="panel-body hidden" id="joined-players">
        </div>
    <%end%>
  <div class="panel panel-default col-xs-6">
    <h4>Ready</h4>
    <div class="panel-body" id="ready-players">
      <% if @ready_players.any? %>
        <% @ready_players.each do |ready_player| %>
          <p id="<%= ready_player.user.username %>"><%= render partial: 'players/show', locals: {player: ready_player} %></p>
        <% end %>
      <%else%>
        <div class="panel-body hidden" id="ready-players">
        </div>
      <%end%>
    </div>
  </div>
</div>

<div class="row col-xs-8 col-xs-offset-2">
  <section>
    <% if @chatroom_player.status == "ready" %>
      <div id="ready-button" class="hidden">
        <%= render partial: 'chatrooms/ready' %>
      </div>
        <br>
      <div id="unready-button" >
        <%= render partial: 'chatrooms/unready' %>
      </div>
        <br>
    <% else %>
      <div id="ready-button">
        <%= render partial: 'chatrooms/ready' %>
      </div>
        <br>
      <div id="unready-button" class="hidden">
        <%= render partial: 'chatrooms/unready' %>
      </div>
        <br>
    <% end %>
  </section>
  <section>
    <%= render partial: 'chatrooms/leave', locals: {chatroom_player: @chatroom_player}%>
  </section>
  <section>
    <% if @chatroom_player.creator == true %>
      <div class="hidden" id="add-arnold-button" >
        <%= render partial: 'chatrooms/add_arnold', locals: {chatroom: @chatroom, arnold_count: @arnolds.count} %>
      </div>
      <div class="hidden" id="remove-arnold-button" >
        <%= render partial: 'chatrooms/remove_arnold', locals: {chatroom: @chatroom, arnold_count: @arnolds.count} %>
      </div>
     <% end %>
  </section>
</div>

<div class="row col-xs-8 col-xs-offset-2">
  <h1><%= @chatroom.topic %></h1>
  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render @chatroom.messages %>
      </div>
    <%else%>
      <div class="panel-body hidden" id="messages">
      </div>
    <%end%>
  </div>
  <% if current_user %>
    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom, chatroom_player: @chatroom_player}%>
  <% end %>
</div>

<div>
  
</div>