config/routes.rb
Rails.application.routes.draw do

  root 'welcome#about'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks", passwords: 'users/passwords' }
  resources :chatrooms, param: :slug
  resources :messages
  resources :pictures
  resources :memes
  resources :votes
  resources :chatroom_players
  get ':slug/waiting', to: "chatrooms#waiting"
  get ':slug/meme', to: "chatrooms#meme"
  get ':slug/vote', to: "chatrooms#vote"
  get ':slug/winner', to: "chatrooms#winner"
  get ':slug', to: 'chatrooms#show'
  post ':slug/addarnold', to: 'chatroom_players#addarnold'
  post ':slug/removearnold', to: 'chatroom_players#removearnold'
  post 'chatrooms/join', to: 'chatrooms#join'

  
  mount ActionCable.server => '/cable'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def about
    @chatroom = Chatroom.new
  end
  
end

app/views/welcome/about.html.erb
<div class="jumbotron">
  <div class="container">
  <br>
    <% unless current_user %>
  <h3 class="text-center">Welcome to Meme Wars!</h3>
  <br>
      <div class="row text-center">
        <p>MemeWars is a game where you compete with your friends to write the funniest caption, or meme, for photos. Login to start playing!</p>
        <div class="col-xs-12">
          <%= link_to "Facebook Login", "/users/auth/facebook", id: "sign_in", class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>

<div class="container text-center">
  <%if current_user%>
    <% if current_user.username %>
  
    <div class="row"><p>Enter a game code to join or create a game below</p></div>
      <div class="row">
        <%= render partial: 'chatrooms/chatroom_join', locals: {chatroom: @chatroom} %>
      </div>
      <br><br>
      <div class="row">
        <%= form_for @chatroom do |f| %>
        <%= f.hidden_field :topic, class: "form-control"%>
        <%= f.submit "Create Private Game", class: "btn btn-primary", id: "create-game" %>
        <% end %>
      </div>
      <br><br>
      <div><p>Public Games Coming Soon!</p></div>
    <%else%>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <p>Please create a user name. We do not share any of your Facebook information, this is the only name other players will see. It can be changed in your profile.</p>
        <div class="auth-form well">
          <%= form_for(:user, url: registration_path(:user), method: 'patch') do |f| %>
            <%=f.label :username%>
            <div class="input-group">
              <span class="input-group-addon">@</span>
                <%= f.text_field :username, class: "form-control"%>
            </div>
            <div class="actions">
              <%= f.submit "Create Username", class: "btn btn-primary" %>
            </div>
        <% end %>
        </div>
      </div>
    <%end%>
  <%end%>
  </div>
</div>