config/routes.rb
Rails.application.routes.draw do

  root 'welcome#about'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks", passwords: 'users/passwords' }
  resources :chatrooms, param: :slug
  resources :messages
  resources :pictures
  resources :memes
  resources :votes
  resources :chatroom_players
  get ':slug/waiting', to: "chatrooms#waiting"
  get ':slug/meme', to: "chatrooms#meme"
  get ':slug/vote', to: "chatrooms#vote"
  get ':slug/winner', to: "chatrooms#winner"
  get ':slug', to: 'chatrooms#show'
  post ':slug/addarnold', to: 'chatroom_players#addarnold'
  post ':slug/removearnold', to: 'chatroom_players#removearnold'
  post 'chatrooms/join', to: 'chatrooms#join'

  
  mount ActionCable.server => '/cable'

end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :chatroom_pictures
  has_many :chatrooms, through: :chatroom_pictures

  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 4.megabytes }
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>',
    large: '600x600>',
    xl: '1200x1200',
  },
  # convert_options: {
  #   thumb: "mogrify -filter Triangle -define filter:support=2 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip INPUT_PATH",
  #   square: "mogrify -filter Triangle -define filter:support=2 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip INPUT_PATH",
  #   medium: "mogrify -filter Triangle -define filter:support=2 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip INPUT_PATH",
  #   large: "mogrify -filter Triangle -define filter:support=2 -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip INPUT_PATH"
  # },
  default_url: "/images/:style/missing.png"

  # Validate the attached image is image/jpg, image/png, etc
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @chatroom = Chatroom.find params[:chatroom_id]
    respond_to do |format|
      if @picture.save!
        @chatroom_picture = ChatroomPicture.new
        @chatroom_picture.picture_id = @picture.id
        @chatroom_picture.chatroom_id = @chatroom.id
        @chatroom_picture.save!
        format.html { redirect_to @chatroom, notice: 'picture was successfully created.' }
        format.json { redirect_to @chatroom, status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:avatar, :category)
    end
end

app/views/pictures/_picture.html.erb
<div class="picture" id="<%= picture.id %>">
  <div class="front">
    <%= link_to picture, class: 'pic-link' do %>
      <%= image_tag picture.avatar.url(:square) %>
    <% end %>
  </div>

  <div class="back">
    <span class="picture-name"><%= picture.category %></span>
    <div class="actions">
      <%= link_to 'Show', picture %>
      <%= link_to 'Edit', edit_picture_path(picture) %>
      <%= link_to 'Delete', picture, confirm: 'Are you sure you want to lose a picture?', method: :delete, class: 'destroy' %>
    </div>
  </div>
</div>

app/views/pictures/_picture_form.html.erb
<%= form_for(@picture, multipart: true) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag(:chatroom_id, @chatroom.id) %>
  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit 'Make a picture' %>
    <%= link_to 'Nevermind', pictures_path, class: 'button' %>
  </div>
<% end %>

app/views/pictures/_quick_pic.html.erb
<%= image_tag picture.avatar.url(:large) %>

app/views/pictures/edit.html.erb
<h1>Change your picture*</h1>

<%= render 'picture_form' %>

app/views/pictures/index.html.erb
<div class="nav-offset container">

  <h2>Make a new picture <%= link_to 'New picture', new_picture_path, class: 'nav-offset new-picture' %></h2>

  <section id="pictures">
    <%= render @pictures %>
  </section>
</div>

app/views/pictures/new.html.erb
<h1>Make a new picture</h1>

<%= render 'picture_form' %>

app/views/pictures/show.html.erb
<div class="nav-offset container">
  <p id="notice"><%= notice %></p>

  <h2><%= @picture.category %></h2>
    <%= image_tag @picture.avatar.url(:medium) %>

  <div class="show actions">
    <%= link_to 'Edit', edit_picture_path(@picture) %>
    <%= link_to 'Remove', @picture, data: { confirm: 'Are you sure you want to lose a picture?' }, method: :delete, class: 'destroy' %>
    <%= link_to 'Back to all my pictures', pictures_path %>
  </div>
</div>